In [16]:
import numpy as np
import pandas as pd

## Conjuntos 
Del modelo de optimización

| **Término** | **Descripción**                |
|------------|--------------------------------|
| $cacopios$ | Conjunto de centros de acopio  |
| $clientes$ | Conjunto de clientes           |
| $productos$ | Conjunto de productos          |

In [17]:
cacopios = 'CAcopios'
clientes = 'Clientes'
productos = 'Productos'

In [18]:
csv_base = './csv/'

routes = {
    # Capacidades de centros de acopio
    'cic': 'CapInvCA.csv',
    'cictest': 'CapInvCAtest.csv',
    # Costo de inventario del centro de acopio
    'cia' : 'CostoInvCA.csv',
    'ciatest' : 'CostoInvCAtest.csv',
    # Costo de transporte del centro de acopio al cliente
    'ctac' : 'CostoTransCAClie.csv',
    'ctactest' : 'CostoTransCAClietest.csv'
}

csv_config = {
    'delimiter' : ';',
    'decimal' : ','
}

## Centros de acopio

In [19]:
cacopios_df = pd.read_csv(csv_base + cacopios + 'test' + '.csv')
cacopios_df

CAcopios
0  San Juan del Cesar
1            Riohacha
2              Maicao

## Clientes

In [20]:
clientes_df = pd.read_csv(csv_base + clientes + 'test' + '.csv')
clientes_df

Clientes
0  Distribuidor1
1  Distribuidor2

## Productos

In [21]:
productos_df = pd.read_csv(csv_base + productos + '.csv')
productos_df.head()

Productos
0    Queso duro
1  Queso blando

# Escenarios de prueba
Tomando demandas por cada centro de acopio, se definen distintos escenarios de posibles casos.

**Escenario 1**: Un centro de acopio sobrepasa la demanda del cliente
- El modelo puede asignar dicho centro de acopio para suplir con la demanda
- El centro de acopio debe proveer esa demanda

**Escenario 2**: Ningún centro de acopio cumple con toda la demanda del cliente
- El modelo debe dar una solución de varios centros de acopio
- La suma de la demanda por cada centro de acopio debe ser igual a la demanda

**Escenario 3**: Un centro de acopio tiene en stock exactamente la cantidad de la demanda de un cliente.
- El modelo puede tomar el centro de acopio que tiene en stock exactamente la demanda a cumplir

### Demandas
Generando demandas para cada cliente, se usarán como entrada para el modelo

In [22]:
demanda_clientes = clientes_df[clientes].drop_duplicates()

demandas = []

for client in demanda_clientes:
    demandas.append(20 * np.random.randint(10))

demanda_clientes = pd.DataFrame(demanda_clientes)

demanda_clientes['Demanda'] = pd.DataFrame(demandas)
demanda_clientes

Clientes  Demanda
0  Distribuidor1       60
1  Distribuidor2        0

### Capacidades 
Obteniendo las capacidades de cada centro de acopio

In [23]:
cap_df = pd.read_csv(csv_base + routes['cictest'], **csv_config)

cap_df

CAcopios     Productos  CapInvCA
0  San Juan del Cesar    Queso duro        50
1  San Juan del Cesar  Queso blando       320
2            Riohacha    Queso duro        60
3            Riohacha  Queso blando        90
4              Maicao    Queso duro       100
5              Maicao  Queso blando         0

#### Costos de Inventario
$$
  CInventario_t = \sum_{j \in J} \sum_{p \in P} CostoInvAcopio_{pjt} InvCA_{pjt} \qquad \forall_t \in T
$$

In [24]:
cia_df = pd.read_csv(csv_base + routes['ciatest'], **csv_config)
cia_df.head()

CAcopios     Productos  CostoInvCA
0  San Juan del Cesar    Queso duro        1000
1  San Juan del Cesar  Queso blando        1500
2            Riohacha    Queso duro         500
3            Riohacha  Queso blando         800
4              Maicao    Queso duro         900

#### Costos de Transporte
$$
  CTransporte_t = \sum_{k \in K} \sum_{j \in J} \sum_{p \in P} CostoTransAcopioClie_{pjkt} \qquad \forall_t \in T
$$

In [25]:
ctac_df = pd.read_csv(csv_base + routes['ctactest'], **csv_config)
ctac_df.head()

CAcopios       Clientes  CostoTransCAClie
0  San Juan del Cesar  Distribuidor1             68000
1  San Juan del Cesar  Distribuidor2             38000
2            Riohacha  Distribuidor1             21000
3            Riohacha  Distribuidor2             15000
4              Maicao  Distribuidor1             99000

## Esquema de representación
Se recibe la demanda $DemandaClie_{pkt}$ como parámetro de entrada.

Se representa la cantidad $n$ de centros de acopio como un vector, donde se asigna una cantidad $x_i$ para cada centro de acopio $J_i$, la cantidad asignada representa la demanda que va a ser suplida por ese centro de acopio.
$$
\begin{array} {|r|r|r|r|r|r|}
    \hline x_0 & x_1 & x_2 & x_3 & \cdots & x_n \\
    \hline
\end{array}
\quad \therefore \quad x_i = AC_{pjkt}
$$
Donde se aplican las restricciones:
$$
\begin{align*}
    \sum_{i=0}^{n} x_i &= DemandaClie_{pkt} \\
    x_i &\leq InvCA_{pjt}
\end{align*}
$$

In [26]:
X = np.zeros(cacopios_df.shape)
# Se toma la primera demanda como parámetro de entrada
demanda = demanda_clientes.loc[0, 'Demanda']

cap_queso = cap_df[cap_df[productos] == 'Queso duro']

for i in range(X.shape[0]):
    rand = np.random.randint(demanda)
    cap = cap_df.loc[i, 'CapInvCA']
        
    if i == X.size - 1 and demanda != 0:
        X[i] = demanda
        demanda -= demanda
    else:
        if rand > cap:
            X[i] = cap
            demanda -= cap
        else:
            X[i] = rand
            demanda -= rand
    
suma_demanda = X.sum()
    
# print(X)
# print(f'Suma de la distribución: {suma_demanda}')

### Cálculo de costos en función objetivo

In [27]:
# Esta función calcula los costos por cada centro de acopio, y los anexa al nombre del centro de acopio, no es necesario mantenerla debido a que este cálculo se hace en la función objetivo, se eliminará pronto

def costos():
    sum_costos_ca = []

    for costo in range(X.shape[0]):
        ca = cacopios_df.loc[costo]
        delta = 0
        
        if X[costo] == 0:
            sum_costos_ca.append((ca.tolist()[0], 0.))
            continue
    
        costo_inv_ca = cia_df[(cia_df[cacopios] == ca[cacopios]) & (cia_df[productos] == 'Queso duro')]
        costo_trans_ca = ctac_df[(ctac_df[cacopios] == ca[cacopios]) & (ctac_df[clientes] == 'Distribuidor1')]
    
        delta += X[costo] * costo_inv_ca['CostoInvCA']
        delta += np.array(costo_trans_ca['CostoTransCAClie'])
    
        sum_costos_ca.append((ca.tolist()[0], delta.tolist()[0]))
        
    return sum_costos_ca

## Función objetivo
$$
Min(F) = CInventario + CTransporte
$$

In [28]:
# Min(F(x))
def f(x):
    delta = 0
    print(f'{x} -> Suma: {x.sum()}')

    for idx in range(x.shape[0]):
        ca = cacopios_df.loc[idx]

        if x[idx] == 0.:
            continue

        # Costos de Inventario
        costo_inv_ca = cia_df[(cia_df[cacopios] == ca[cacopios]) & (cia_df[productos] == 'Queso duro')]
        # Costos de Transporte
        costo_trans_ca = ctac_df[(ctac_df[cacopios] == ca[cacopios]) & (ctac_df[clientes] == 'Distribuidor1')]

        delta += x[idx] * costo_inv_ca['CostoInvCA'].values[0]
        delta += np.array(costo_trans_ca['CostoTransCAClie'].values[0])
    
    if np.round(x.sum()) != suma_demanda:
        delta *= 2
    
    return delta

print(f'Costo: {f(X)}')

[[43.]
 [ 1.]
 [16.]] -> Suma: 60.0
Costo: [245900.]


## scipy

**LinearConstraint**: $ lb \leq A*v[x] \leq ub $

**NonLinearConstraint**: $ lb \leq g(x) \leq ub $

In [29]:
from scipy.optimize import LinearConstraint
from scipy.optimize import NonlinearConstraint

cons = {'constraints': LinearConstraint(np.ones(X.shape[0]), suma_demanda, suma_demanda)}

g = lambda x : x.sum()
non_cons = {'constraints': NonlinearConstraint(g, suma_demanda, suma_demanda)}


In [30]:
from scipy.optimize import dual_annealing
# from scipy.optimize import differential_evolution

bounds = [(0, x_i) for x_i in cap_queso['CapInvCA']]
x0 = [x[0] for x in X]
        
result = dual_annealing(
    f,
    bounds=bounds,
    minimizer_kwargs=cons,
    maxiter=200,
    x0=np.array(x0)
)
print(result)

[43.  1. 16.] -> Suma: 60.0
[27.81635165 55.81635165 87.03461681] -> Suma: 170.66732011549175
[ 5.32151093 45.51573499 40.51573499] -> Suma: 91.35298090428114
[41.10734271  6.92047177 41.92047177] -> Suma: 89.94828625023365
[10.26757516  1.         16.        ] -> Suma: 27.267575159668922
[43.         38.40792943 16.        ] -> Suma: 97.40792942792177
[43.          1.         36.80107566] -> Suma: 80.80107565782964
[43.  1. 16.] -> Suma: 60.0
[43.00000001  1.         16.        ] -> Suma: 60.00000001490116
[43.          1.00000001 16.        ] -> Suma: 60.00000001490116
[43.          1.         16.00000001] -> Suma: 60.00000001490116
[-157.  301.  -84.] -> Suma: 60.000000000000014
[-156.99999999  301.          -84.        ] -> Suma: 60.000000014901175
[-157.          301.00000001  -84.        ] -> Suma: 60.000000014901175
[-157.          301.          -83.99999999] -> Suma: 60.000000014901175
[-1157.  1801.  -584.] -> Suma: 59.999999999999886
[-1156.99999999  1801.          -584.     